### ISSUE TITLE
Issue with scraping EBE results

### ISSUE THREAD

**Issue by An-Shank** [AbhijithAsokan/Cusat-BTech-Result-Scraper#1]
The EB subject codes don't have spaces in them. So they are throwing up errors

**Comment by abhijithasokan** [comment]
Fixed

**Comment by An-Shank** [comment]
Mass



‌

*C A Anand Shankar*
Placement Cell Coordinator
Govt. Model Engineering College, Kochi
[image: Inline image 3] caanandshankar.mec@gmail.com
[image: Inline image 3] caanandshankar@mec.ac.in
[image: Inline image 2] +91-8281410562
