### ISSUE TITLE
Issue with Scraping 7th Sem Nov 2017 Results

### ISSUE THREAD

**Issue by An-Shank** [AbhijithAsokan/Cusat-BTech-Result-Scraper#2]
In the code, 'type_of_exam' : "Regular" is running fine. But when I put in type of exam as:
'type_of_exam' : "Revaluation" , the following error pops up:
Traceback (most recent call last):
  File "getMarks2.py", line 207, in <module>
    name = re.search('<th>Student Name</th><td>(.*?)</td>',res_page).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

I've attached a screenshot of the same.
![screenshot_20180516_120100](https://user-images.githubusercontent.com/23638829/40100581-06412e36-5902-11e8-87c1-c8186901f668.png)

**Comment by abhijithasokan** [comment]
You are running an old version of the code.
Please pull the changes and try again. It works fine for me.
